import { Laptop, Monitor, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import Card from '../../../components/common/Card'
import FilterPills from '../../../components/common/FilterPills'
import Modal from '../../../components/common/Modal'
import PageHeader from '../../../components/common/PageHeader'
import StatusBadge from '../../../components/common/StatusBadge'
import { FormField, SelectField } from '../../../components/common/FormField'
import { fmtDate } from '../../../components/common/date'
import { useEms } from '../../../context/EmsContext'

export default function AssetsPage() {
  const { db, role, allowedAssets, currentAssetAssignment, employeeById, registerAsset, assignAsset, returnAsset }=useEms()
  const [filter,setFilter]=useState('All')
  const [registerOpen,setRegisterOpen]=useState(false)
  const [manage,setManage]=useState(null)
  const assets=useMemo(()=>allowedAssets().filter(a=>filter==='All'||a.status===filter),[db,role,filter])
  return <><PageHeader title={role==='admin'?'Asset & equipment management':'My assets'} description={role==='admin'?'Register, assign, return and track company equipment.':'Assets currently assigned to you.'} actions={role==='admin'&&<button onClick={()=>setRegisterOpen(true)} className="bg-[#1A1D1F] dark-primary text-white rounded-full px-4 py-2.5 text-xs font-bold flex items-center gap-2"><Plus className="w-4 h-4"/>Register asset</button>}/>{role==='admin'&&<FilterPills items={['All','Available','Assigned','Maintenance','Damaged','Lost','Retired']} value={filter} onChange={setFilter}/>}<Card><div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr className="text-left text-[10px] uppercase tracking-wider text-app-muted muted"><th className="pb-3">Asset</th><th className="pb-3">Type</th><th className="pb-3">Serial</th><th className="pb-3">Assigned to</th><th className="pb-3">Assigned date</th><th className="pb-3">Status</th>{role==='admin'&&<th/>}</tr></thead><tbody>{assets.map(a=>{const asn=currentAssetAssignment(a.id);const Icon=a.category==='Monitor'?Monitor:Laptop;return <tr key={a.id} className="border-t border-app-border"><td className="py-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-app-subtle subtle flex items-center justify-center"><Icon className="w-4 h-4"/></div><div><div className="text-xs font-bold txt">{a.name}</div><div className="text-[10px] text-app-muted muted">{a.id}</div></div></div></td><td className="py-4 text-xs font-semibold txt">{a.category}</td><td className="py-4 text-[10px] font-mono text-app-muted muted">{a.serial}</td><td className="py-4 text-xs font-semibold txt">{asn?employeeById(asn.employee)?.name:'—'}</td><td className="py-4 text-xs text-app-muted muted">{asn?fmtDate(asn.assignedDate):'—'}</td><td className="py-4"><StatusBadge status={a.status}/></td>{role==='admin'&&<td className="py-4 text-right"><button onClick={()=>setManage(a)} className="px-3 py-2 rounded-full border border-gray-200 text-[10px] font-bold">Manage</button></td>}</tr>})}</tbody></table></div></Card><RegisterAsset open={registerOpen} onClose={()=>setRegisterOpen(false)} onSave={a=>{registerAsset(a);setRegisterOpen(false)}}/><ManageAsset asset={manage} db={db} assignment={manage?currentAssetAssignment(manage.id):null} onClose={()=>setManage(null)} onAssign={(assetId,eid)=>{assignAsset(assetId,eid);setManage(null)}} onReturn={assetId=>{returnAsset(assetId);setManage(null)}}/></>
}

function RegisterAsset({open,onClose,onSave}) { const [form,setForm]=useState({name:'',category:'Laptop',serial:''});return <Modal open={open} onClose={onClose} title="Register asset" subtitle="Add company equipment to the asset register." footer={<><button onClick={onClose} className="px-4 py-2.5 rounded-full border border-gray-200 text-xs font-bold">Cancel</button><button onClick={()=>onSave(form)} className="px-4 py-2.5 rounded-full bg-[#1A1D1F] dark-primary text-white text-xs font-bold">Register</button></>}><div className="grid gap-4"><FormField label="Asset name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><SelectField label="Asset type" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Laptop','Monitor','Specialized device','Peripheral','Camera','Tablet'].map(x=><option key={x}>{x}</option>)}</SelectField><FormField label="Serial number" value={form.serial} onChange={e=>setForm({...form,serial:e.target.value})}/></div></Modal> }
function ManageAsset({asset,db,assignment,onClose,onAssign,onReturn}) { const [employee,setEmployee]=useState('E004');if(!asset)return null;return <Modal open={!!asset} onClose={onClose} title={asset.name} subtitle={`${asset.id} · ${asset.serial}`} footer={assignment?<button onClick={()=>onReturn(asset.id)} className="px-4 py-2.5 rounded-full bg-app-green-bg text-app-green text-xs font-bold">Return asset</button>:asset.status==='Available'?<button onClick={()=>onAssign(asset.id,employee)} className="px-4 py-2.5 rounded-full bg-[#1A1D1F] dark-primary text-white text-xs font-bold">Assign asset</button>:null}><div className="space-y-4"><StatusBadge status={asset.status}/>{assignment?<div className="subtle bg-app-subtle p-4 rounded-2xl text-xs"><div className="font-bold txt">Currently assigned to {db.employees.find(e=>e.id===assignment.employee)?.name}</div><div className="text-app-muted muted mt-1">Since {assignment.assignedDate}</div></div>:asset.status==='Available'?<SelectField label="Assign to employee" value={employee} onChange={e=>setEmployee(e.target.value)}>{db.employees.filter(e=>e.status==='Active').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</SelectField>:<p className="text-xs text-app-muted muted">This asset is not currently available for assignment.</p>}</div></Modal> }
